services:
  - type: web
    name: terra-alta
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    redirects:
      - source: /*
        destination: /index.html
        status: 200
