services:
  - type: static_site
    name: terra-alta
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Robots-Tag
        value: index, follow
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
